### ISSUE TITLE
ver con nacho

### ISSUE THREAD

**Issue by LucasNatoli** [CiervoCreativo/floresadry#15]
API keys de paypal
Tokens mercado pago

Horarios de entrega/recepcion de pedidos

Productos anexados (regalos) cuales son?
Definir las secciones que faltan cargar 
Fotos de los productos

**Comment by CiervoCreativo** [comment]
Paso los tokens de mercado pago. 

client_id: aaaaaaaaaaaaaaaaaaaaa

client_secret: oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Nacho me debe los de paypal.

Horarios: rangos horarios de 3 hs para elegir a que hora hacer la entrega del pedido.
6-9 / 9-12 / 12-15 / 15-18 / 18-21

**Comment by LucasNatoli** [comment]
ok las pasarelas de pago, queda ver el plugin de time slots
