### ISSUE TITLE
CARGA DE ZONAS

### ISSUE THREAD

**Issue by CiervoCreativo** [CiervoCreativo/floresadry#3]
Te adjunto el pdf con los precios de cada zona.
[GASTOS DE ENTREGA WEB POR LOCALIDAD.pdf](https://github.com/CiervoCreativo/floresadry/files/2354391/GASTOS.DE.ENTREGA.WEB.POR.LOCALIDAD.pdf)

**Comment by LucasNatoli** [comment]
listo
